#!/usr/bin/env python3
"""Simple HTTP server for the SAE Feature Activation Explorer webapp.

This server loads the CSV file generated by analyze_sae_activations.py and
serves it as JSON to the web frontend.

Usage:
    python server.py --csv sae_feature_activations.csv --port 8000
"""
import argparse
import csv
import json
from pathlib import Path
from http.server import HTTPServer, SimpleHTTPRequestHandler
import urllib.parse


class SAEServerHandler(SimpleHTTPRequestHandler):
    """HTTP handler that serves the webapp and data API."""

    csv_path = None
    pca_path = None

    def __init__(self, *args, **kwargs):
        # Set the directory to serve files from
        super().__init__(*args, directory=str(Path(__file__).parent), **kwargs)

    def do_GET(self):
        """Handle GET requests."""
        parsed_path = urllib.parse.urlparse(self.path)

        if parsed_path.path == '/data':
            self.serve_data()
        elif parsed_path.path == '/pca_data':
            self.serve_pca_data()
        else:
            # Serve static files (HTML, JS, CSS)
            super().do_GET()

    def serve_data(self):
        """Serve the CSV data as JSON."""
        try:
            if not self.csv_path or not Path(self.csv_path).exists():
                self.send_error(404, f"CSV file not found: {self.csv_path}")
                return

            # Load CSV data
            rows = []
            with open(self.csv_path, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    rows.append({
                        'sae_type': row['sae_type'],
                        'feature_idx': int(row['feature_idx']),
                        'activation_value': float(row['activation_value']),
                        'manifold_name': row['manifold_name'],
                        'prompt': row['prompt']
                    })

            # Prepare response
            response_data = {
                'total_rows': len(rows),
                'rows': rows
            }

            # Send response
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()

            self.wfile.write(json.dumps(response_data).encode('utf-8'))

        except Exception as e:
            self.send_error(500, f"Error loading data: {str(e)}")

    def serve_pca_data(self):
        """Serve pre-computed PCA projections as JSON."""
        try:
            if not self.pca_path or not Path(self.pca_path).exists():
                self.send_error(404, f"PCA data not found: {self.pca_path}. Run: python generate_pca_data.py")
                return

            with open(self.pca_path, 'r', encoding='utf-8') as f:
                pca_data = json.load(f)

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(json.dumps(pca_data).encode('utf-8'))

        except Exception as e:
            self.send_error(500, f"Error loading PCA data: {str(e)}")

    def log_message(self, format, *args):
        """Custom log message to make it cleaner."""
        if self.path.startswith('/data'):
            print(f"[API] {self.command} {self.path} - {args[1]}")
        else:
            print(f"[STATIC] {self.command} {self.path}")


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        '--csv',
        type=str,
        default='../sae_feature_activations.csv',
        help='Path to the CSV file generated by analyze_sae_activations.py (default: ../sae_feature_activations.csv)'
    )
    parser.add_argument(
        '--pca',
        type=str,
        default='../pca_data.json',
        help='Path to the JSON file generated by generate_pca_data.py (default: ../pca_data.json)'
    )
    parser.add_argument(
        '--port',
        type=int,
        default=8000,
        help='Port to run the server on (default: 8000)'
    )
    parser.add_argument(
        '--host',
        type=str,
        default='localhost',
        help='Host to bind to (default: localhost)'
    )

    args = parser.parse_args()

    # Resolve CSV path
    csv_path = Path(args.csv).resolve()
    if not csv_path.exists():
        print(f"Error: CSV file not found: {csv_path}")
        print(f"\nPlease run analyze_sae_activations.py first to generate the CSV file.")
        return 1

    # Set paths on the handler class
    SAEServerHandler.csv_path = csv_path

    pca_path = Path(args.pca).resolve()
    SAEServerHandler.pca_path = pca_path
    if not pca_path.exists():
        print(f"Warning: PCA data not found at {pca_path}")
        print("Run: python generate_pca_data.py   (the 3D PCA view will be unavailable)")
    else:
        print(f"PCA data: {pca_path}")

    # Print startup info
    print("=" * 60)
    print("SAE Feature Activation Explorer")
    print("=" * 60)
    print(f"CSV file: {csv_path}")
    print(f"Server: http://{args.host}:{args.port}")
    print(f"\nOpen http://{args.host}:{args.port} in your browser")
    print("\nPress Ctrl+C to stop the server")
    print("=" * 60)

    # Check CSV file size
    csv_size = csv_path.stat().st_size
    csv_size_mb = csv_size / (1024 * 1024)
    print(f"\nCSV file size: {csv_size_mb:.2f} MB")

    if csv_size_mb > 100:
        print(f"Warning: Large CSV file ({csv_size_mb:.2f} MB). Loading may be slow.")
        print(f"Consider using --top-n option in analyze_sae_activations.py to reduce file size.")

    # Count rows
    with open(csv_path, 'r', encoding='utf-8') as f:
        row_count = sum(1 for _ in f) - 1  # Subtract header
    print(f"Total rows: {row_count:,}")

    # Start server
    try:
        server = HTTPServer((args.host, args.port), SAEServerHandler)
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n\nShutting down server...")
        server.shutdown()
        return 0
    except Exception as e:
        print(f"\nError starting server: {e}")
        return 1


if __name__ == '__main__':
    exit(main())
